### ISSUE TITLE
I got one trouble at the first step

### ISSUE THREAD

**Issue by yoohan-dex** [blackjack0v0/mpvuesimple-quickstart#1]
![image](https://user-images.githubusercontent.com/7565496/42409410-b2ec6050-820c-11e8-8b4d-4aa05773f2c0.png)

I can't do anything about that =。=

**Comment by blackjack0v0** [comment]
@yoohan-dex     check  your nodejs and npm version  

Prerequisites: Node.js (>=6.x, 8.x preferred), npm version 3+ and Git.

**Comment by yoohan-dex** [comment]
![image](https://user-images.githubusercontent.com/7565496/42412104-b61143a0-8238-11e8-9c1b-68f0fb30f32e.png)
I have installed the exact correct  version dependency ..
![image](https://user-images.githubusercontent.com/7565496/42412115-e1e5be70-8238-11e8-9d60-9b5761064235.png)
and I grabbed the error message image

**Comment by blackjack0v0** [comment]
can you show you detail steps  when you init your project？

**Comment by blackjack0v0** [comment]
ok!!!I figure out the probrems, you miss  this step 
`git clone https://github.com/blackjack0v0/static`

**Comment by blackjack0v0** [comment]
@yoohan-dex   I fix the parser probrem ,try to init from the first step ,and you will get away form this error message
