### ISSUE TITLE
npm run dev后生成dist文件缺少app.js/project.config.json等文件

### ISSUE THREAD

**Issue by windole** [blackjack0v0/mpvuesimple-quickstart#2]
你好，如题，使用你的模板生成项目后，打包时会缺失部分文件

**Comment by blackjack0v0** [comment]
@windole  程序可以运行吗？具体有截图看一下吗

**Comment by blackjack0v0** [comment]
@windole   修复了,是mpvue-loader新版本的问题，我已经更新了template/package.json中的mpvue-loader版本限制为1.0.13，重新初始化下就可以解决了
